name: run node with different versions using include and exclude
on:
  push:
    branches:
      - matrixWorkflow
jobs:
  run_matrix_with_exclude:
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]
        node_version: [6, 8, 10]
        exclude:
          - os: windows-latest
            node_version: 6
        include:
          - os: ubuntu-latest
            node_version: 10
          - is_ubuntu_8: "true"
        
        
      fail-fast: false
    env:
      IS_UBUNTU_8: ${{matrix.is_ubuntu_8}}  
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - name: run node version
        run: |
          node -v 
          echo $IS_UBUNTU_8 

